import { Inter } from 'next/font/google';
import "./globals.css";
import SmoothScrollProvider from "./components/SmoothScrollProvider"; // Import the smooth scroll provider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Apply smooth scrolling globally */}
        <SmoothScrollProvider>
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}